#!/usr/bin/env bash
REPO=$1

if [ -z "$REPO" ]
then
	echo "repo cannot be empty"
	exit 1
fi

cd ${HOME}/code/itps
git clone git@github.com:newmoon-org/${REPO}.git
cd ./${REPO}
git config user.name "enpfeff"
git config user.email "enpfeff@gmail.com"
